version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mosuuuutech
      MONGO_INITDB_ROOT_PASSWORD: mosuuuutech

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGODB_URL: mongodb://mosuuuutech:mosuuuutech@mongodb:27017/golang_challenge?authSource=admin
      JWT_SECRET: secret-jwt-key-for-production